"""Add dim_hour and drop fact timestamps

Revision ID: e5f6a7b8c9d0
Revises: d4e5f6a7b8c9
Create Date: 2026-07-08
"""

from alembic import op

revision = "e5f6a7b8c9d0"
down_revision = "d4e5f6a7b8c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        create table analyst.dim_hour (
            hour_key integer generated by default as identity primary key,
            date_key integer not null references analyst.dim_date(date_key),
            observed_date date not null,
            observed_at timestamptz not null unique
        )
        """
    )
    op.execute(
        """
        insert into analyst.dim_hour (date_key, observed_date, observed_at)
        select distinct date_key, observed_date, observed_at
        from analyst.fact_weather_hourly
        order by observed_at
        """
    )
    op.execute(
        "create index if not exists ix_dim_hour_observed_date "
        "on analyst.dim_hour(observed_date)"
    )

    _upgrade_hourly_table("fact_weather_hourly")
    _upgrade_hourly_table("fact_aqi_hourly")

    op.execute("alter table analyst.fact_weather_daily drop column created_at")
    op.execute("alter table analyst.fact_weather_daily drop column updated_at")


def downgrade() -> None:
    op.execute(
        "alter table analyst.fact_weather_daily "
        "add column created_at timestamptz not null default now()"
    )
    op.execute(
        "alter table analyst.fact_weather_daily "
        "add column updated_at timestamptz not null default now()"
    )

    _downgrade_hourly_table("fact_aqi_hourly")
    _downgrade_hourly_table("fact_weather_hourly")

    op.execute("drop table analyst.dim_hour")


def _upgrade_hourly_table(table_name: str) -> None:
    op.execute(f"drop index if exists analyst.ix_{table_name}_observed_at")
    op.execute(f"alter table analyst.{table_name} drop constraint {table_name}_pkey")
    op.execute(f"alter table analyst.{table_name} add column hour_key integer")
    op.execute(
        f"""
        update analyst.{table_name} fact
        set hour_key = hour.hour_key
        from analyst.dim_hour hour
        where hour.observed_at = fact.observed_at
        """
    )
    op.execute(f"alter table analyst.{table_name} alter column hour_key set not null")
    op.execute(
        f"alter table analyst.{table_name} "
        f"add constraint {table_name}_hour_key_fkey foreign key (hour_key) "
        "references analyst.dim_hour(hour_key)"
    )
    op.execute(
        f"alter table analyst.{table_name} "
        f"add constraint {table_name}_pkey primary key (district_id, hour_key)"
    )
    op.execute(f"alter table analyst.{table_name} drop column date_key")
    op.execute(f"alter table analyst.{table_name} drop column observed_date")
    op.execute(f"alter table analyst.{table_name} drop column observed_at")
    op.execute(f"alter table analyst.{table_name} drop column created_at")
    op.execute(f"alter table analyst.{table_name} drop column updated_at")


def _downgrade_hourly_table(table_name: str) -> None:
    op.execute(f"alter table analyst.{table_name} add column date_key integer")
    op.execute(f"alter table analyst.{table_name} add column observed_date date")
    op.execute(f"alter table analyst.{table_name} add column observed_at timestamptz")
    op.execute(f"alter table analyst.{table_name} add column created_at timestamptz")
    op.execute(f"alter table analyst.{table_name} add column updated_at timestamptz")
    op.execute(
        f"""
        update analyst.{table_name} fact
        set date_key = hour.date_key,
            observed_date = hour.observed_date,
            observed_at = hour.observed_at
        from analyst.dim_hour hour
        where hour.hour_key = fact.hour_key
        """
    )
    op.execute(f"alter table analyst.{table_name} alter column date_key set not null")
    op.execute(f"alter table analyst.{table_name} alter column observed_date set not null")
    op.execute(f"alter table analyst.{table_name} alter column observed_at set not null")
    op.execute(f"alter table analyst.{table_name} drop constraint {table_name}_pkey")
    op.execute(f"alter table analyst.{table_name} drop constraint {table_name}_hour_key_fkey")
    op.execute(f"alter table analyst.{table_name} drop column hour_key")
    op.execute(
        f"alter table analyst.{table_name} "
        f"add constraint {table_name}_pkey primary key (district_id, observed_at)"
    )
    op.execute(
        f"create index if not exists ix_{table_name}_observed_at "
        f"on analyst.{table_name}(observed_at)"
    )
